src/Lulhum/RepartitionMedecineBundle/Entity/Requirement.php
<?php

namespace Lulhum\RepartitionMedecineBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Requirement
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Lulhum\RepartitionMedecineBundle\Repository\RequirementRepository")
 */
class Requirement
{

    const TYPES = array(
        'maxPlaces' => 'Nombre de places maximum',
        'promotion' => 'Promotion',
        'group' => 'Groupe',
        'maxChoicesInPeriod' => 'Maximum de choix pour cette période',
        'maxStagesInPeriod' => 'Maximum de stages pour cette période',
        'maxStagesInStageCategory' => 'Maximum de stages avec ce modèle',
        'maxChoicesInStageCategory' => 'Maximum de choix avec ce modèle',
        'maxChoicesInStageCategoryWithinSchoolyear' => 'Maximum de choix avec ce modèle dans la même année',
        'maxStagesInStageCategoryWithinScoolyear' => 'Maximum de stages avec ce modèle dans la même année',
        'maxStagesInCategory' => 'Maximum de stages dans la catégorie',
        'maxChoicesInCategory' => 'Maximum de choix dans la catégorie',
        'maxChoicesInCategoryWithinSchoolyear' => 'Maximum de choix avec dans la catégorie dans la même année',
        'maxStagesInCategoryWithinSchoolyear' => 'Maximum de stages avec dans la catégorie dans la même année',
    );
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(name="params", type="string", length=255)
     */
    private $params;

    /**
     * @var boolean
     *
     * @ORM\Column(name="strict", type="boolean")
     */
    private $strict;

    /**
     * @ORM\ManyToOne(targetEntity="Lulhum\RepartitionMedecineBundle\Entity\StageProposal", inversedBy="requirements")
     * @ORM\JoinColumn(nullable=false)
     */     
    private $proposal;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return Requirement
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set params
     *
     * @param array $params
     * @return Requirement
     */
    public function setParams($params)
    {
        $this->params = $params;

        return $this;
    }

    /**
     * Get params
     *
     * @return array 
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Set strict
     *
     * @param boolean $strict
     * @return Requirement
     */
    public function setStrict($strict)
    {
        $this->strict = $strict;

        return $this;
    }

    /**
     * Get strict
     *
     * @return boolean 
     */
    public function getStrict()
    {
        return $this->strict;
    }

    /**
     * Set proposal
     *
     * @param \Lulhum\RepartitionMedecineBundle\Entity\StageProposal $proposal
     * @return Requirement
     */
    public function setProposal($proposal)
    {
        $this->proposal = $proposal;

        return $this;
    }

    /**
     * Get proposal
     *
     * @return \Lulhum\RepartitionMedecineBundle\Entity\StageProposal
     */
    public function getProposal()
    {
        return $this->proposal;
    }

    public function __toString()        
    {
        return self::TYPES[$this->getType()].': '.$this->getParams();
    }

    public function getTextType()
    {
        return self::TYPES[$this->getType()];
    }

    public function text($categories = array())
    {
        $response = self::TYPES[$this->getType()];
        if($this->getType() === 'promotion') {
            $response .= ': '.\Lulhum\UserBundle\Entity\User::PROMOTIONS[$this->getParams()];
        }
        elseif($this->getType() === 'maxStagesInCategory' || $this->getType() === 'maxChoicesInCategory') {
            $response .= ' "'.$categories[$this->getParamsArray()[0]].'": '.$this->getParamsArray()[1];
        }
        else {
            $response .= ': '.$this->getParams();
        }

        return $response;
    }

    public function getParamsArray($index = null)
    {
        $paramsArray = preg_split("/[,{}]/", $this->getParams(), -1, PREG_SPLIT_NO_EMPTY);
        if(is_null($index)) {
            
            return $paramsArray;
        }
        if(array_key_exists($index, $paramsArray)) {

            return $paramsArray[$index];
        }

        if(count($paramsArray) > 0) {
            
            return $paramsArray[0];
        }

        return null;
    }
        
}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/categories.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/categories.html.twig #}
{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}
{% block title %}
	Catégories - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3>Gestion des catégories</h3>				
{% endblock %}

{% block nobody %}
	<table class="table table-hover" >
		<tr>
			<th>Nom</th>
			<th>Description</th>
			<th>Utilisations</th>
			<th>Actions</th>
		</tr>
		{% for category in categories %}
			<tr>
				<td>{{ category.name }}</td>
				<td>{{ category.description }}</td>
				<td>
					<a href="{{ path('lulhum_repartitionmedecine_admin_stage_categories_incategory', {'id': category.id}) }}" >
						{{ category.stageCategories|length }} Modèles
					</a>
				</td>
				<td>
					<a href="{{ path('lulhum_repartitionmedecine_admin_categories_edit', {'id': category.id}) }}">
						<span class="glyphicon glyphicon-edit" ></span>
					</a>
					<a href="{{ path('lulhum_repartitionmedecine_admin_categories_delete', {'id': category.id}) }}" class="text-danger">
						<span class="glyphicon glyphicon-remove" ></span>
					</a>
				</td>
			</tr>
		{% endfor %}
	</table>
{% endblock %}

{% block bodyunder %}
	<span class="text-primary" >
		<span class="glyphicon glyphicon-edit" ></span>
	</span>
	Éditer la catégorie -
	<span class="text-danger" >
		<span class="glyphicon glyphicon-remove" ></span>
	</span>
	Supprimer la catégorie
{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/confirm.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/confirm.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
  Confirmation - {{ parent() }}
{% endblock %}

{% block main %}
	<div class="panel panel-danger" >
		<div class="panel-heading" >
			Confirmation
		</div>
		<div class="panel-body" >
			{{ message }}
		</div>
		<div class="panel-footer" >
			{{ form_start(form) }}
			{{ form_widget(form.Confirmer) }}
			<a href="{{ app.request.headers.get('referer') }}" class="btn btn-primary" >Annuler</a>
			{{ form_rest(form) }}
			{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/editlocation.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/editlocation.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
Lieu - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3>Éditer le lieu</h3>
{% endblock %}

{% block nobody %}
	{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
	<div class="panel-body" >
		{% include('LulhumRepartitionMedecineBundle:Admin:location_type.html.twig') %}
	</div>
	<div class="panel-footer" >
		<button class="btn btn-success" type="submit" >Éditer</button>
	</div>		
	{{ form_rest(form) }}
	{{ form_end(form) }}
{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/groupactionlist.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/groupactionlist.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block nobody %}

	{% if app.session.flashbag.all()|length > 0 %}
		<div class="panel-body" >
			{% for key, messages in app.session.flashbag.all() %}
				{% for message in messages %}
					<div class="alert alert-{{ key }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endfor %}
		</div>
	{% endif %}

	{{ form_start(groupActionForm, {'attr': {'class': 'form-inline'}}) }}
	<table class="table table-hover">
		<tr>
			<th><input type="checkbox" id="master-check" /></th>
			{% block groupactionlisthead %}{% endblock %}
		</tr>
		{% for child in groupActionForm.entities %}
			<tr>
				<td>{{ form_widget(child) }}</td>
				{% block groupactionlistbody %}{% endblock %}
			</tr>
		{% endfor %}
	</table>
	<div class="panel-footer" >
		{% include "LulhumRepartitionMedecineBundle:Admin:pagination.html.twig" %}
		<div class="form-group" >
			{{ form_label(groupActionForm.action, null, {'label_attr': {'class': 'control-label'}}) }}
			{{ form_errors(groupActionForm.action) }}
			{{ form_widget(groupActionForm.action, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="form-group" >
			<button type="submit" class="btn btn-primary" >Appliquer</button>
		</div>
		{{ form_rest(groupActionForm) }}
	</div>
	{{ form_end(groupActionForm) }}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script type="text/javascript" >
	$(document).ready(function() {
		$('input#master-check').change(function() {
			var $checkboxes = $('form[name="lulhum_repartitionmedecine_groupaction"] :checkbox');
			$checkboxes.prop('checked', $(this).prop('checked'));
		});
	});
	</script>
{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/location_type.html.twig
<div class="form-group" >
	{{ form_label(form.name, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.name) }}
	<div class="col-md-10" >
		{{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
<div class="form-group" >
	{{ form_label(form.description, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.description) }}
	<div class="col-md-10" >
		{{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
<div class="form-group" >
	{{ form_label(form.distance, 'Distance', {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.distance) }}
	<div class="col-md-10" >
		<div class="input-group" >
			{{ form_widget(form.distance, {'attr': {'class': 'form-control'}}) }}
			<span class="input-group-addon">km</span>
		</div>
	</div>
</div>

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/opengrouprepartition.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/useradd.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
	Ouvrir la répartition de groupe {{ promotion }} - {{ parent() }}
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{% stylesheets '@datepicker_css' %}
	<link rel="stylesheet" type="text/css" media="screen" href="{{ asset_url }}"/>
        {% endstylesheets %}
{% endblock %}

{% block bodytitle %}
	<h3 class="panel-title" >Ouvrir la répartition de groupe {{ promotion }}</h3>
{% endblock %}

{% block body %}
	{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
	<div class="form-group" >
		{{ form_label(form.date, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
		{{ form_errors(form.date) }}
		<div class="col-md-10" >
			{{ form_widget(form.date, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
	<div class="form-group" >
		{{ form_label(form.delay, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
		{{ form_errors(form.delay) }}
		<div class="col-md-1" >
			{{ form_label(form.delay.hour, 'Heure', {'label_attr': {'class': 'control-label'}}) }}
			{{ form_errors(form.delay.hour) }}
			{{ form_widget(form.delay.hour, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="col-md-1" >
			{{ form_label(form.delay.minute, null, {'label_attr': {'class': 'control-label'}}) }}
			{{ form_errors(form.delay.minute) }}
			{{ form_widget(form.delay.minute, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
	<div class="form-group" >
			{{ form_label(form.reset, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
			{{ form_errors(form.reset) }}
			<div class="col-md-1" >
				{{ form_widget(form.reset, {'attr': {'class': 'form-control'}}) }}
			</div>
		</div>
		{{ form_widget(form.ouvrir, {'attr': {'class': 'btn btn-primary'}, 'label': 'Démarrer'}) }}
	{{ form_rest(form) }}
	{{ form_end(form) }}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{% javascripts '@datepicker_js' %}
	<script type="text/javascript" src="{{ asset_url }}"></script>
	{% endjavascripts %}
	<script type="text/javascript" >
	$(document).ready(function() {
		$('#lulhum_deadline_deadline_date').datetimepicker({
			locale: 'fr',
			minDate: (new Date()).setHours(0, 0, 0, 0)
		});
	});
	</script>		
{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/periods.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/periods.html.twig #}
{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}
{% block title %}
	Périodes - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3>Gestion des périodes</h3>				
{% endblock %}

{% block nobody %}
	<table class="table table-hover" >
		<tr>
			<th>Nom</th>
			<th>Description</th>
			<th>Début</th>
			<th>Fin</th>
			<th>Utilisations</th>
			<th>Actions</th>
		</tr>
		{% for period in periods %}
			<tr>
				<td>{{ period.name }}</td>
				<td>{{ period.description }}</td>
				<td>{{ period.start|date('d/m/Y') }}</td>
				<td>{{ period.stop|date('d/m/Y') }}</td>
				<td>
					<a href="{{ path('lulhum_repartitionmedecine_admin_stage_proposals_inperiod', {'id': period.id}) }}" >
						{{ period.proposals|length }} Propositions
					</a>
				</td>
				<td>
					<a href="{{ path('lulhum_repartitionmedecine_admin_periods_edit', {'id': period.id}) }}">
						<span class="glyphicon glyphicon-edit" ></span>
					</a>
					{% if period.proposals|length == 0 %}
						<a href="{{ path('lulhum_repartitionmedecine_admin_periods_delete', {'id': period.id}) }}" class="text-danger">
							<span class="glyphicon glyphicon-remove" ></span>
						</a>
					{% else %}
						<span class="glyphicon glyphicon-remove" ></span>
					{% endif %}
				</td>
			</tr>
		{% endfor %}
	</table>
{% endblock %}

{% block bodyunder %}
	<span class="text-primary" >
		<span class="glyphicon glyphicon-edit" ></span>
	</span>
	Éditer la période -
	<span class="text-danger" >
		<span class="glyphicon glyphicon-remove" ></span>
	</span>
	Supprimer la période
{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/repartitiongroupindex.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/repartitiongroupindex.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
	Répartition des Groupes - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3>Groupes de répartition</h3>
{% endblock %}

{% block body %}	

	{% set promotions = {'DFASM1': 'DFASM 1', 'DFASM2': 'DFASM 2'} %}
	{% set expanded = false %}
	{% set admin = true %}

	{% for promotion, promotionTitle in promotions %}

		<h3>{{ promotionTitle }}</h3>

		<p>
			Répartition:
			{% if deadline[promotion].active %}
				<span class="label label-success" >En Cours</span>				
				<a href="{{ path('lulhum_repartitionmedecine_admin_repartitiongroup_stop', {'promotion': promotion}) }}" class="btn btn-primary">
					<span class="badge" >
						{{ deadline[promotion].date|date('d/m - H:i') }} +{{ deadline[promotion].delay|date('H:i') }}
						<span class="glyphicon glyphicon-time" ></span>
					</span>
					Stop
				</a>
			{% else %}
				<span class="label label-danger" >Terminée</span>
				<a href="{{ path('lulhum_repartitionmedecine_admin_repartitiongroup_start', {'promotion': promotion}) }}" class="btn btn-primary">Démarrer</a>
			{% endif %}		
		</p>

		{% set userListGroups = userListGroupsAll[promotion] %}
		{% include "LulhumRepartitionMedecineBundle:Repartition:groupes_content.html.twig" %}
		
	{% endfor %}
	
{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/stageproposalgroupaction.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/stageproposalgroupaction.html.twig #}

{% extends "LulhumRepartitionMedecineBundle:Admin:groupaction.html.twig" %}

{% block groupactionbodytitle %}Propositions de stage - {{ parent() }}{% endblock %}

{% block groupactionaffectedentities %}Propositions affectées{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/stageproposals.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/stageproposals.html.twig #}

{% extends "LulhumRepartitionMedecineBundle:Admin:groupactionlist.html.twig" %}

{% block title %}
  Propositions de stage - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3>Gestion des propositions de stage</h3>
	<hr/>
	{{ form_start(filterForm, {'attr': {'class': 'form-inline'}}) }}
	{{ form_errors(filterForm) }}
	<div class="form-group" >
		{{ form_label(filterForm.periods, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.periods) }}
		{{ form_widget(filterForm.periods, {'attr': {'class': 'form-control', 'multiple': 'true', 'size': '2'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(filterForm.stageCategories, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.stageCategories) }}
		{{ form_widget(filterForm.stageCategories, {'attr': {'class': 'form-control', 'multiple': 'true', 'size': '2'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(filterForm.categoriesOr, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.categoriesOr) }}
		{{ form_widget(filterForm.categoriesOr, {'attr': {'class': 'form-control', 'multiple': 'true', 'size': '2'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(filterForm.categoriesAnd, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.categoriesAnd) }}
		{{ form_widget(filterForm.categoriesAnd, {'attr': {'class': 'form-control', 'multiple': 'true', 'size': '2'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(filterForm.promotions, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.promotions) }}
		{{ form_widget(filterForm.promotions, {'attr': {'class': 'form-control', 'multiple': 'true', 'size': '2'}}) }}
	</div>
	<br/>
	<div style="margin-top:10px" >
		<div class="form-group" >
			{{ form_widget(filterForm.filtrer, {'attr': {'class': 'btn btn-primary' }}) }}
		</div>
		<div class="form-group" >				
			<a class="btn btn-primary" href="{{ path('lulhum_repartitionmedecine_admin_stage_proposals_resetfilter') }}">Filtre par défaut</a>
		</div>
		<div class="form-group" >				
			<a class="btn btn-primary" href="{{ path('lulhum_repartitionmedecine_admin_stage_proposals_nofilter') }}">Aucun filtre</a>
		</div>
		<div class="form-group" >				
			<a class="btn btn-success" href="{{ path('lulhum_repartitionmedecine_admin_stage_proposals_new') }}">Nouvelle proposition</a>
		</div>
	</div>
	{{ form_rest(filterForm) }}
	{{ form_end(filterForm) }}
	{% for key, messages in app.session.flashbag.all() %}
		{% if loop.first %}<hr/>{% endif %}
		{% for message in messages %}
			<div class="alert alert-{{ key }} alert-dismissible">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
		{% endfor %}
	{% endfor %}
{% endblock %}

{% block groupactionlisthead %}
	<th>Nom</th>
	<th>Période</th>
	<th>Modèle</th>
	<th>Contraintes</th>
	<th>Inscrits</th>
	<th>Active</th>
	<th>Actions</th>
{% endblock %}

{% block groupactionlistbody %}
	<td>
		<a href="{{ path('lulhum_repartitionmedecine_admin_stage_proposals_show', {'id': stageProposals[loop.index0].id}) }}" >
			{{ stageProposals[loop.index0].name }}
		</a>
	</td>
	<td>
		{% if stageProposals[loop.index0].period.description is not null %}
			{{ stageProposals[loop.index0].period.description }}
		{% else %}
			{{ stageProposals[loop.index0].period }}
		{% endif %}
	</td>
	<td>
		<a href="{{ path('lulhum_repartitionmedecine_admin_stage_categories_show', {'id': stageProposals[loop.index0].category.id}) }}">
			{{ stageProposals[loop.index0].category }}
		</a>
	</td>
	<td>
		<div class="dropdown" >
			<button class="btn btn-default dropdown-toggle" type="button" id="requirements-for-stage-proposal-{{ loop.index0 }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
				Contraintes
				<span class="badge">{{ stageProposals[loop.index0].requirements|length }}</span>
				<span class="caret" ></span>
			</button>
			<ul class="dropdown-menu" aria-labelledby="requirements-for-stage-proposal-{{ loop.index0 }}" >
				{% for requirement in stageProposals[loop.index0].requirements %}
					<li><a href="">
						{% if requirement.type == 'promotion' %}
							{{ requirement.textType }}: {{ promotions[requirement.params] }}
						{% elseif requirement.type in ['maxStagesInCategory', 'maxChoicesInCategory'] %}
							{{ requirement.textType }}
							"{{ categories[requirement.paramsArray[0]] }}":
							{{ requirement.paramsArray[1] }}
						{% else %}
							{{ requirement }}
						{% endif %}
					</a></li>
				{% endfor %}
			</ul>
		</div>
	</td>
	<td>	
		{% if stageProposals[loop.index0].hasRequirementType('maxPlaces') %}
			{% set maxPlaces = stageProposals[loop.index0].getRequirementsByType('maxPlaces').first.params %}
			{% set usedPlaces = stageProposals[loop.index0].stages.count %}
			<div class="label label-{% if maxPlaces < usedPlaces %}danger{% elseif maxPlaces == usedPlaces %}warning{% else %}success{% endif %}" >
				{{ usedPlaces }}
				/						
				{{ maxPlaces }}
			</div>
		{% else %}
			<div class="label label-success" >
				{{ stageProposals[loop.index0].stages.count }}
				/
				&infin;
			</div>
		{% endif %}
	</td>
	<td>
		{% if stageProposals[loop.index0].locked %}
			{% if stageProposals[loop.index0].deadline is not null %}
				{% set deadline = stageProposals[loop.index0].deadline %}							
				<button type="button"
					class="btn btn-danger btn-xs"
					data-container="body"
					data-toggle="popover"
					data-placement="right"
					data-trigger="click"
					data-content="{{ deadline.date|date('d/m - H:i') }} +{{ deadline.delay|date('H:i') }}" >
					Non -
					<span class="glyphicon glyphicon-time" ></span>
				</button>
			{% else %}
				<span class="label label-danger" >Non</span>
			{% endif %}
		{% else %}
			{% if stageProposals[loop.index0].deadline is not null %}
				{% set deadline = stageProposals[loop.index0].deadline %}							
				<button type="button"
					class="btn btn-success btn-xs"
					data-container="body"
					data-toggle="popover"
					data-placement="right"
					data-trigger="click"
					data-content="{{ deadline.date|date('d/m - H:i') }} +{{ deadline.delay|date('H:i') }}" >
					Oui -
					<span class="glyphicon glyphicon-time" ></span>
				</button>
			{% else %}
				<span class="label label-success" >Oui</span>
			{% endif %}
		{% endif %}
	</td>
	<td>
		<a href="{{ path('lulhum_repartitionmedecine_admin_stage_stages_inproposal', {'id': stageProposals[loop.index0].getId()}) }}">
			<span class="glyphicon glyphicon-share" ></span>
		</a>
		<a href="{{ path('lulhum_repartitionmedecine_admin_stage_proposals_edit', {'id': stageProposals[loop.index0].getId()}) }}">
			<span class="glyphicon glyphicon-edit" ></span>
		</a>
		<a href="{{ path('lulhum_repartitionmedecine_admin_stage_proposals_delete', {'id': stageProposals[loop.index0].getId()}) }}" class="text-danger">
			<span class="glyphicon glyphicon-remove" ></span>
		</a>
	</td>
{% endblock %}
			
{% block bodyunder %}
	<div>
		<span class="text-primary" >
			<span class="glyphicon glyphicon-share" ></span>
		</span>
		Voir les stages correspondants -
		<span class="text-primary" >
			<span class="glyphicon glyphicon-edit" ></span>
		</span>
		Éditer la proposition -
		<span class="text-danger" >
			<span class="glyphicon glyphicon-remove" ></span>
		</span>
		Supprimer la proposition
	</div>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script type="text/javascript" >
	$(document).ready(function() {			
		$(function () {
			$('[data-toggle="popover"]').popover()
		})
	});
	</script>
{% endblock %}