src/Lulhum/RepartitionMedecineBundle/Entity/StageProposal.php
<?php

namespace Lulhum\RepartitionMedecineBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Lulhum\UserBundle\Entity\User;

/**
 * StageProposal
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Lulhum\RepartitionMedecineBundle\Repository\StageProposalRepository")
 */
class StageProposal
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Lulhum\RepartitionMedecineBundle\Entity\Period", inversedBy="proposals", cascade={"persist", "merge"})
     * @ORM\JoinColumn(nullable=false)
     */   
    private $period;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="Lulhum\RepartitionMedecineBundle\Entity\StageCategory", inversedBy="proposals", cascade={"merge"})
     * @ORM\JoinColumn(nullable=false)
     */  
    private $category;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description=null;

    /**
     * @var boolean
     *
     * @ORM\Column(name="locked", type="boolean")
     */
    private $locked=true;

    /**
     * @ORM\ManyToOne(targetEntity="Lulhum\DeadlineBundle\Entity\Deadline")
     * @ORM\JoinColumn(nullable=true)
     */  
    private $deadline;

    /**
     * @ORM\OneToMany(targetEntity="Lulhum\RepartitionMedecineBundle\Entity\Requirement", mappedBy="proposal", cascade={"persist", "remove"})
     */  
    private $requirements;

    /**
     * @ORM\OneToMany(targetEntity="Lulhum\RepartitionMedecineBundle\Entity\Stage", mappedBy="proposal", cascade={"remove"})
     */  
    private $stages;

    public function __construct()
    {
        $this->requirements = new ArrayCollection();
        $this->stages = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    private function setId($id)
    {
        $this->id = $id;
    }

    /**
     * Set period
     *
     * @param \Lulhum\RepartitionMedecineBundle\Entity\Period $period
     * @return StageProposal
     */
    public function setPeriod($period)
    {
        $this->period = $period;

        return $this;
    }

    /**
     * Get period
     *
     * @return \Lulhum\RepartitionMedecineBundle\Entity\Period
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return StageProposal
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        if(is_null($this->name) && !is_null($this->getCategory()) && !is_null($this->getPeriod())) {

            return $this->getCategory().' - '.$this->getPeriod();
        }        

        return $this->name;
    }

    /**
     * Set category
     *
     * @param \Lulhum\RepartitionMedecineBundle\Entity\StageCategory $category
     * @return StageProposal
     */
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return \Lulhum\RepartitionMedecineBundle\Entity\StageCategory
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return StageProposal
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        if(is_null($this->description) && !is_null($this->category) && !is_null($this->category->getDescription())) {

            return $this->category->getDescription();
        }
        
        return $this->description;
    }

    /**
     * Set locked
     *
     * @param boolean $locked
     * @return StageProposal
     */
    public function setLocked($locked)
    {
        $this->locked = $locked;

        return $this;
    }

    /**
     * Get locked
     *
     * @return boolean 
     */
    public function getLocked()
    {
        return $this->locked;
    }

    /**
     * Set deadline
     *
     * @param \Lulhum\DeadlineBundle\Entity\Deadline $deadline
     * @return StageProposal
     */
    public function setDeadline($deadline)
    {
        $this->deadline = $deadline;

        return $this;
    }

    /**
     * Get deadline
     *
     * @return \Lulhum\DeadlineBundle\Entity\Deadline
     */
    public function getDeadline()
    {
        return $this->deadline;
    }

    public function setRequirements(ArrayCollection $requirements)
    {
        foreach($requirements as $requirement) {
            $requirement->setProposal($this);
        }

        $this->requirements = $requirements;

        return $this;
    }

    public function getRequirements()
    {
        return $this->requirements;
    }

    public function addRequirement(Requirement $requirement)
    {
        $requirement->setProposal($this);
        $this->requirements[] = $requirement;

        return $this;
    }

    public function removeRequirement(Requirement $requirement)
    {
        $this->requirements->removeElement($requirement);

        return $this;
    }

    public function newPeriod()
    {
        return new Period();
    }

    public function setNewPeriod(Period $period)
    {
        if(is_null($period->getName())) {

            return $this;
        }
        
        return $this->setPeriod($period);
    }

    public function __toString()
    {
        try {
            
            return $this->getName();
        }
        catch(\Exception $e) {
            echo $e->getMessage();
            
            return '#';
        }
    }     

    public function setStages(ArrayCollection $stages)
    {
        foreach($stages as $stage) {
            $stage->setProposal($this);
        }

        $this->stages = $stages;

        return $this;
    }

    public function getStages()
    {
        return $this->stages;
    }

    public function getSortedStages()
    {
        $iterator = $this->stages->getIterator();
        $iterator->uasort(function($a, $b) {
            if($a->getUser()->getFullname() === $b->getUser()->getFullname()) return 0;
            return $a->getUser()->getFullname() < $b->getUser()->getFullname() ? -1 : 1;
        });
        
        return new ArrayCollection(iterator_to_array($iterator));
    }        

    public function addStage(Stage $stage)
    {
        $stage->setProposal($this);
        $this->stages[] = $stage;

        return $this;
    }

    public function removeStage(Stage $stage)
    {
        $this->stages->removeElement($stage);

        return $this;
    }

    public function hasRequirementType($type)
    {
        return $this->requirements->exists(function($key, $requirement) use (&$type) {
            return $requirement->getType() === $type;
        });
    }

    public function getRequirementsByType($type)
    {
        return $this->requirements->filter(function($requirement) use (&$type) {
            return $requirement->getType() === $type;
        });
    }

    public function getPromotion()
    {
        if(!$this->hasRequirementType('promotion')) {
            return null;
        }

        return $this->getRequirementsByType('promotion')->first()->getParams();
    }

    public function countPlaces()
    {
        if($this->hasRequirementType('maxPlaces')) {
            
            return (int)($this->getRequirementsByType('maxPlaces')->first()->getParams()) - $this->getStages()->count();
        }
        
        return PHP_INT_MAX;
    }

    public function hasUser(User $user)
    {
        return $this->stages->exists(function($key, $stage) use (&$user) {
            return $stage->getUser()->getId() === $user->getId();
        });
    }

    public function getStagesByUser(User $user)
    {
        return $this->stages->filter(function($stage) use (&$user) {
            return $stage->getUser()->getId() === $user->getId();
        });
    }

    public function isValidForUser(User $user, \Lulhum\RepartitionMedecineBundle\Util\StageValidator $validator, $notValidOnWarning = false)
    {
        $stage = new Stage($user, $this);
        $valid = $validator->isValid($stage, $notValidOnWarning);
        $this->removeStage($stage);
        $user->removeStage($stage);

        return $valid;
    }

    public function getValidity(User $user, \Lulhum\RepartitionMedecineBundle\Util\StageValidator $validator)
    {
        $stage = new Stage($user, $this);
        $validity = $validator->getValidity($stage);
        $this->removeStage($stage);
        $user->removeStage($stage);

        return $validity;
    }

    public function __clone()
    {
        if($this->id) {
            $this->setId(null);
            $requirements = $this->getRequirements();
            $this->requirements = new ArrayCollection();
            foreach($requirements as $requirement) {
                $cloneRequirement = clone $requirement;
                $this->requirements->add($cloneRequirement);
                $cloneRequirement->setProposal($this);
            }
        }
    }
            
}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/groupes.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/groupes.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::layout.html.twig" %}

{% block title %}
  Choix des groupes - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3>Répartition des groupes - {{ app.user.textPromotion }}</h3>
	{% if deadline.active %}
		{{ form_start(form, {'attr': {'class': 'form-inline'}}) }}
		<div class="form-group" >
			{{ form_label(form.repartitionGroup, null, {'label_attr': {'class': 'control-label'}}) }}
			{{ form_errors(form.repartitionGroup) }}
			{{ form_widget(form.repartitionGroup, {'attr': {'class': 'form-control'}}) }}
		</div>
		<button class="btn btn-success" type="submit" >Valider</button>
		{{ form_rest(form) }}
		{{ form_end(form) }}
		<div class="label label-primary">
			Répartition ouverte jusqu'au {{ deadline.date|date('d/m - H:i') }}
			<span class="glyphicon glyphicon-time" ></span>
		</div>
	{% else %}
		<div>Groupe {{ app.user.repartitionGroup }}</div>
	{% endif %}
{% endblock %}

{% block body %}
	<div class="row" >
		<div>
			{% for key, messages in app.session.flashbag.all() %}
				{% for message in messages %}
					<div class="alert alert-{{ key }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endfor %}
		</div>

		<div class="col-md-6" >
			<div class="panel panel-default" >
				<div class="panel-heading" >
					<strong>Périodes pour le groupe A:</strong>
				</div>
				<div class="panel-body" >
					{% if app.user.promotion == 'DFASM1' %}
						Octobre-Novembre<br/>
						Février-Mars<br/>
						Juin-Juillet
					{% else %}
						Décembre-Janvier<br/>
						Avril-Mai<br/>
						Août-Septembre
					{% endif %}
				</div>
			</div>
		</div>
		<div class="col-md-6" >
			<div class="panel panel-default" >
				<div class="panel-heading" >
					<strong>Périodes pour le groupe B:</strong>
				</div>
				<div class="panel-body" >
					{% if app.user.promotion == 'DFASM1' %}
						Décembre-Janvier<br/>
						Avril-Mai<br/>
						Août-Septembre			
					{% else %}
						Octobre-Novembre<br/>
						Février-Mars<br/>
						Juin-Juillet
					{% endif %}
				</div>
			</div>	
		</div>
	</div>
	
	{% set expanded = false %}
	{% set admin = false %}
	{% include "LulhumRepartitionMedecineBundle:Repartition:groupes_content.html.twig" %}

{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/groupes_content.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/groupes_content.html.twig #}

<div class="row">
	{% for key, userListGroup in userListGroups %}
		{% if key not in ['limit', 'none'] %}
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<span style="margin-right:20px">
							<a role="button" data-toggle="collapse" href="#repartitiongroup{{ promotion }}{{ key }}" aria-expanded=" {{ expanded ? 'true':'false' }}" aria-controls="repartitiongroup{{ promotion }}{{ key }}">
								Groupe {{ key }}
							</a>
						</span>						
						<span class="label label-{% if userListGroup|length > userListGroups['limit']  %}danger{% else %}success{% endif %}">	
							{{ userListGroup|length }}/{{ userListGroups['limit'] }}
						</span>
					</div>
					<div class="collapse{{ expanded ? ' in':'' }}" id="repartitiongroup{{ promotion }}{{ key }}">
						<table class="table">
							{% for u in userListGroup %}
								<tr>
									{% if admin %}
										<td>{{ loop.index }}</td>
										{% if key == 'B' %}
											<td>
												<a href="{{ path('lulhum_repartitionmedecine_admin_repartitiongroup_switchuser', {'id': u.id}) }}">
													<span class="glyphicon glyphicon-arrow-left" ></span>
												</a>
											</td>
										{% endif %}
										<td>
											<a href="{{ path('lulhum_user_admin_user', {'id': u.id}) }}">
												{{ u.fullname }}
											</a>
										</td>
										<td>{{ u.repartitionGroupRequestedAt|date('d/m - H:i') }}</td>
										<td>{% if u.repartitionGroupForce %}<span class="glyphicon glyphicon-lock" ></span>{% endif %}</td>
										{% if key == 'A' %}
											<td>
												<a href="{{ path('lulhum_repartitionmedecine_admin_repartitiongroup_switchuser', {'id': u.id}) }}">
													<span class="glyphicon glyphicon-arrow-right" ></span>
												</a>
											</td>
										{% endif %}
									{% else %}
										<td>{{ u.fullname }}</td>
									{% endif %}
								</tr>
							{% endfor %}
						</table>
					</div>
				</div>
			</div>
		{% endif %}
	{% endfor %}
</div>

src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/index.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/index.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block body %}
	{% for key, messages in app.session.flashbag.all() %}
		{% for message in messages %}
			<div class="alert alert-{{ key }} alert-dismissible">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
		{% endfor %}
	{% endfor %}
	<h2>Bienvenue {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}{{ app.user.firstname }} {{ app.user.lastname }}{% endif %}</h2>
{% endblock %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/menu.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/menu.html.twig #}

{% for item in listItems %}
	<li>
		<a href="{{ path(item.path, item.options) }}">
			{{ item.label }}
		</a>
	</li>
{% endfor %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/proposalinfo.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/proposalinfo.html.twig #}

<div class="row" >
	<div class="col-md-2" >Places:</div>
	<div class="col-md-10" >
		{% set taked = proposal.stages.count %}
		{% if proposal.hasRequirementType('maxPlaces') %}
			{% set max = proposal.getRequirementsByType('maxPlaces').first.params %}
			<span class="label label-{% if taked > max %}danger{% elseif taked == max %}warning{% else %}success{% endif %}" >
				{{ taked  }}/{{ max }}
			</span>
		{% else %}
			<span class="label label-success" >{{ taked }}/&infin;</span>
		{% endif %}
	</div>
</div>
<div class="row" >
	<div class="col-md-2" >Période:</div>
	<div class="col-md-10" >{{ proposal.period.description }}</div>
</div>					
{% if proposal.deadline is not null %}
	<div class="row" >
		<div class="col-md-2" >Fin des inscriptions:</div>
		<div class="col-md-10" >{{ proposal.deadline.date|date('d/m - H:i') }}</div>
	</div>
{% endif %}
<div class="row" >
	<div class="col-md-2" >Lieu:</div>
	<div class="col-md-10" >
		{{ proposal.category.location }}
		(Distance: {{ proposal.category.location.distance }}km)
	</div>
</div>
<div class="row" >
	<div class="col-md-2" >Catégories:</div>
	<div class="col-md-10" >
		{% for category in proposal.category.categories %}
			{{ category }}
			{% if not loop.last %},{% endif %}
		{% endfor %}
	</div>							
</div>
{% if proposal.description is not null %}
	<div class="row" >
		<div class="col-md-2" >Description:</div>						
	</div>
	<div class="well">{{ proposal.description }}</div>							
{% endif %}
{% if proposal.stages|length > 0 %}
	<div class="row" >
		<div class="col-md-2" >Utilisateurs inscrits:</div>						
	</div>
	<ul class="list-group" >
		{% for stage in proposal.sortedStages %}
			<li class="list-group-item{% if stage.locked %} list-group-item-success{% endif %}" >
				{{ stage.user.fullname }}
			</li>
		{% endfor %}
	</ul>	
{% endif %}
{% if not admin %}
	{% if valid %}
		<a href="{{ path('lulhum_repartitionmedecine_stages_suscribe', {'id': proposal.id}) }}" class="btn btn-primary" style="margin-top:10px">
			S'inscrire au stage
		</a>
	{% elseif proposal.hasUser(app.user, validator) and not proposal.locked and not proposal.stagesByUser(app.user).first.locked %}
		<a href="{{ path('lulhum_repartitionmedecine_stages_unsuscribe', {'id': proposal.id}) }}" class="btn btn-danger" style="margin-top:10px">
			Annuler l'inscription
		</a>
	{% endif %}
{% else %}
	{% if proposal.requirements|length > 0 %}
	<div class="row" >
		<div class="col-md-2" >Contraintes:</div>						
	</div>
	<ul class="list-group" >
		{% for requirement in proposal.requirements %}
			<li class="list-group-item" >
				{{ requirement.text(categories) }}
			</li>
		{% endfor %}
	</ul>	
{% endif %}
{% endif %}

src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/stages.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Repartition/stages.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::layout.html.twig" %}

{% block title %}
  Choix des stages - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<ul class="nav nav-tabs">
		<li role="presentation" >
			<a href="{{ path('lulhum_repartitionmedecine_stages_calendar') }}">Calendrier</a>
		</li>
		<li role="presentation" {% if type == 'proposals' %}class="active"{% endif %}>
			<a href="{{ path('lulhum_repartitionmedecine_stages_proposals') }}">Propositions</a>
		</li>
		<li role="presentation" {% if type == 'pending' %}class="active"{% endif %}>
			<a href="{{ path('lulhum_repartitionmedecine_stages_pending') }}">Mes Demandes</a>
		</li>
		<li role="presentation" {% if type == 'accepted' %}class="active"{% endif %}>
			<a href="{{ path('lulhum_repartitionmedecine_stages_accepted') }}">Stages Acceptés</a>
		</li>
	</ul>
	{% if type == 'proposals' %}
		Trier par:
		<div class="btn-toolbar" role="toolbar" >
			<div class="btn-group" role="group" >
				<a class="btn btn-default" href="{{ path('lulhum_repartitionmedecine_stages_proposals_sorted', {'sort': 'title'}) }}" >
					Intitulé
				</a>
				<a class="btn btn-default" href="{{ path('lulhum_repartitionmedecine_stages_proposals_sorted', {'sort': 'places'}) }}" >
					Places
				</a>
				<a class="btn btn-default" href="{{ path('lulhum_repartitionmedecine_stages_proposals_sorted', {'sort': 'period'}) }}" >
					Période
				</a>
			</div>
			<div class="col-md-4" >			
				{{ form_start(form) }}
				<div class="input-group" >
					{{ form_widget(form.search, {'attr': {'class': 'form-control', 'placeholder': 'Rechercher...'}}) }}
					<span class="input-group-btn" >
						<button class="btn btn-default" type="submit" >
							<span class="glyphicon glyphicon-search" ></span>
						</button>
					</span>
				</div>
				{{ form_rest(form) }}
				{{ form_end(form) }}
			</div>
		</div>
	{% endif %}
{% endblock %}

{% block body %}
	{% for key, messages in app.session.flashbag.all() %}
		{% for message in messages %}
			<div class="alert alert-{{ key }} alert-dismissible">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
		{% endfor %}
	{% endfor %}
	{% if proposals|length == 0 %}
		<div class="alert alert-info" role="alert" >
			{% if type == 'proposals' %}
				Aucune proposition disponible
			{% elseif type == 'pending' %}
				Aucune demande en cours
			{% elseif type == 'accepted' %}
				Aucun stage accepté
			{% endif %}
		</div>
	{% else %}
		{% for proposal in proposals %}
			<div class="panel panel-{% if validator is null or proposal.isValidForUser(app.user, validator, true) %}default{% else %}warning{% endif %}" >
				<div class="panel-heading" >					
					{{ proposal.name }}
					<button class="btn btn-default" role="button" data-toggle="collapse" href="#proposal-info-{{ proposal.id }}" aria-expanded="false" aria-controls="proposal-info-{{ proposal.id }}" >
						Détails <span class="glyphicon glyphicon-zoom-in" ></span>
					</button>
					{% if type == 'proposals' %}
						<a href="{{ path('lulhum_repartitionmedecine_stages_suscribe', {'id': proposal.id}) }}" class="btn btn-primary" >
							S'inscrire au stage
						</a>
					{% elseif type == 'pending' and not proposal.locked() %}
						<a href="{{ path('lulhum_repartitionmedecine_stages_unsuscribe', {'id': proposal.id}) }}" class="btn btn-danger" >
							Annuler l'inscription
						</a>
					{% endif %}
				</div>
				<div class="panel-body" >	
					<div class="row" >
						<div class="col-md-2" >Places:</div>
						<div class="col-md-10" >
							{% set taked = proposal.stages.count %}
							{% if proposal.hasRequirementType('maxPlaces') %}
								{% set max = proposal.getRequirementsByType('maxPlaces').first.params %}
								<span class="label label-{% if taked > max %}danger{% elseif taked == max %}warning{% else %}success{% endif %}" >
									{{ taked  }}/{{ max }}
								</span>
							{% else %}
								<span class="label label-success" >{{ taked }}/&infin;</span>
							{% endif %}
						</div>
					</div>
					<div class=" collapse" id="proposal-info-{{ proposal.id }}" >
						<div class="row" >
							<div class="col-md-2" >Période:</div>
							<div class="col-md-10" >{{ proposal.period.description }}</div>
						</div>					
						{% if proposal.deadline is not null %}
							<div class="row" >
								<div class="col-md-2" >Fin des inscriptions:</div>
								<div class="col-md-10" >{{ proposal.deadline.date|date('d/m - H:i') }}</div>
							</div>
						{% endif %}
						<div class="row" >
							<div class="col-md-2" >Lieu:</div>
							<div class="col-md-10" >
								{{ proposal.category.location }}
								(Distance: {{ proposal.category.location.distance }}km)
							</div>
						</div>
						<div class="row" >
							<div class="col-md-2" >Catégories:</div>
							<div class="col-md-10" >
								{% for category in proposal.category.categories %}
									{{ category }}
									{% if not loop.last %},{% endif %}
								{% endfor %}
							</div>							
						</div>
						{% if proposal.description is not null %}
							<div class="row" >
								<div class="col-md-2" >Description:</div>						
							</div>
							<div class="well">{{ proposal.description }}</div>							
						{% endif %}
						{% if proposal.stages|length > 0 %}
							<div class="row" >
								<div class="col-md-2" >Utilisateurs inscrits:</div>						
							</div>
							<ul class="list-group" >
								{% for stage in proposal.sortedStages %}
									<li class="list-group-item{% if stage.locked %} list-group-item-success{% endif %}" >
										{{ stage.user.fullname }}
									</li>
								{% endfor %}
							</ul>	
						{% endif %}
						
					</div>
				</div>
			</div>
		{% endfor %}
	{% endif %}
{% endblock %}