src/Lulhum/UserBundle/Entity/User.php
<?php
// src/Lulhum/UserBundle/Entity/User.php

namespace Lulhum\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use FOS\UserBundle\Model\User as BaseUser;
use Lulhum\RepartitionMedecineBundle\Entity\Stage;
use Lulhum\RepartitionMedecineBundle\Entity\Period;

/**
 * @ORM\Entity(repositoryClass="Lulhum\UserBundle\Repository\UserRepository")
 */
class User extends BaseUser
{

    // /!\ Must also change the values list in the annotation field of the promotion attribute. Not very clean but no easy workaround...
    const PROMOTIONS = array(
        'PACES' => 'PACES',
        'L2' => 'L2',
        'L3' => 'L3',
        'DFASM1' => 'DFASM 1',
        'DFASM2' => 'DFASM 2',
        'DFASM3' => 'DFASM 3'
    );

    const GROUPS = array(
        'A' => 'A',
        'B' => 'B',
    );
    
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="firstname", type="string")
     */
    private $firstname;

    /**
     * @ORM\Column(name="lastname", type="string")
     */
    private $lastname;

    /**
     * @ORM\Column(name="student_id", type="string", length=10, unique=true)
     */
    private $studentId;

    /**
     * @ORM\Column(name="phone", type="string", length=10)
     */
    private $phone;

    /**
     * @ORM\Column(name="promotion", type="string", nullable=true, columnDefinition="enum('PACES', 'L2', 'L3', 'DFASM1', 'DFASM2', 'DFASM3')")
     */
    private $promotion;

    /**
     * @ORM\Column(name="present", type="string", columnDefinition="enum('Oui', 'Non', 'Variable')")
     */
    private $present;

    /**
     * @ORM\Column(name="internet_access", type="string", columnDefinition="enum('Oui', 'Non', 'Variable')")
     */
    private $internetAccess;

    /**
     * @ORM\ManyToOne(targetEntity="Lulhum\UserBundle\Entity\User")
     */
    private $proxy;

    /**
     * @ORM\Column(name="repartition_group", type="string", nullable=true, columnDefinition="enum('A', 'B')")
     */
    private $repartitionGroup;

    /**
     * @ORM\Column(name="repartition_group_requested_at", type="datetime", nullable=true)
     */
    private $repartitionGroupRequestedAt;

    /**
     * @ORM\Column(name="repartition_group_force", type="boolean")
     */
    private $repartitionGroupForce = False;

    /**
     * @ORM\OneToMany(targetEntity="Lulhum\RepartitionMedecineBundle\Entity\Stage", mappedBy="user", cascade={"remove"})
     */
    private $stages;

    public function __construct()
    {
        parent::__construct();
        $this->stages = new ArrayCollection();
    }

    public function setRepartitionGroup($repartitionGroup)
    {
        $this->repartitionGroup = $repartitionGroup;
        $this->repartitionGroupRequestedAt = new \DateTime();
        
        return $this;
    }

    public function getRepartitionGroup()
    {
        return $this->repartitionGroup;
    }

    public function getTextRepartitionGroup()
    {
	if(is_null($this->repartitionGroup)) {

	    return 'Indéfini';
	}

        return $this->repartitionGroup;
    }

    public function getRepartitionGroupRequestedAt()
    {
        return $this->repartitionGroupRequestedAt;
    }

    private function setRepartitionGroupRequestedAt($repartitionGroupRequestedAt) {
        $this->repartitionGroupRequestedAt = null;

        return $this;
    }

    public function setRepartitionGroupForce($repartitionGroupForce)
    {
        $this->repartitionGroupForce = $repartitionGroupForce;

        return $this;
    }

    public function getRepartitionGroupForce()
    {
        return $this->repartitionGroupForce;
    }

    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFirstname()
    {
        return $this->firstname;
    }

    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getLastname()
    {
        return $this->lastname;
    }

    public function getFullname()
    {
        return $this->lastname.' '.$this->firstname;
    }

    public function setStudentId($studentId)
    {
        $this->studentId = $studentId;

        return $this;
    }

    public function getStudentId()
    {
        return $this->studentId;
    }

    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPhone()
    {
        return $this->phone;
    }

    public function setPromotion($promotion)
    {
        $this->promotion = $promotion;

        return $this;
    }

    public function getPromotion()
    {
        return $this->promotion;
    }

    public function getTextPromotion()
    {
        if(array_key_exists($this->getPromotion(), self::PROMOTIONS)) {
            
            return self::PROMOTIONS[$this->getPromotion()];
        }
        elseif(is_null($this->getPromotion())) {

            return 'Non défini';
        }
        else {

            return $this->getPromotion();
        }
    }

    public function setPresent($present)
    {
        $this->present = $present;

        return $this;
    }

    public function getPresent()
    {
        return $this->present;
    }

    public function setInternetAccess($internetAccess)
    {
        $this->internetAccess = $internetAccess;

        return $this;
    }

    public function getInternetAccess()
    {
        return $this->internetAccess;
    }

    public function setProxy(User $proxy = null)
    {
        $this->proxy = $proxy;

        return $this;
    }

    public function getProxy()
    {
        return $this->proxy;
    }

    public function getTextProxy()
    {
	if(is_null($this->proxy)) {

	    return 'Non Renseigné';
	}

        return $this->proxy->getFullname();
    }

    public function setEmail($email)
    {
        $this->setUsername($email);

        return parent::setEmail($email);
    }

    public function setEmailCanonical($emailCanonical)
    {
        $this->setUsernameCanonical($emailCanonical);

        return parent::setEmailCanonical($emailCanonical);
    }

    public function getPromotionChoicesValues()
    {
        return self::PROMOTIONS;
    }

    public function __toString()
    {
        return $this->getFullname();
    }

    public function resetRepartitionGroup() {
        $this->setRepartitionGroup(null);
        $this->setRepartitionGroupForce(null);
        $this->setRepartitionGroupRequestedAt(null);
    }

    public function switchRepartitionGroup() {        
        if($this->repartitionGroup == 'A') {
            $this->setRepartitionGroup('B');
        }
        else {
            $this->setRepartitionGroup('A');
        }
    }

    public function getStages()
    {
        return $this->stages;
    }

    public function setStages(ArrayCollection $stages)
    {
        $this->stages = $stages;
    }

    public function addStage(Stage $stage)
    {
        $stage->setUser($this);
        $this->stages[] = $stage;

        return $this;
    }

    public function removeStage(Stage $stage)
    {
        $this->stages->removeElement($stage);

        return $this;
    }

    public function hasStageInPeriod(Period $period)
    {
        return $this->stages->filter(function($stage) use (&$period) {
            return $stage->getProposal()->getPeriod()->getId() === $period->getId();
        })->count() > 0;
    }        

    public function getStageInPeriod(Period $period)
    {
        return $this->stages->filter(function($stage) use (&$period) {
            return $stage->getProposal()->getPeriod()->getId() === $period->getId();
        })->first();
    }        

    public function countStagesInCategory($categoryId, $locked = null)
    {
        if(is_null($locked)) {
            return $this->stages->filter(function($stage) use (&$categoryId) {
                return $stage->getProposal()->getCategory()->getCategories()->exists(function($key, $category) use (&$categoryId) {
                    return $category->getId() === (int)$categoryId;
                });
            })->count();
        }
        else {
            return $this->stages->filter(function($stage) use (&$categoryId, &$locked) {
                return $stage->getLocked() === $locked && $stage->getProposal()->getCategory()->getCategories()->exists(function($key, $category) use (&$categoryId) {
                    return $category->getId() === (int)$categoryId;
                });
            })->count();
        }        
    }

    public function countStagesInCategoryWithinSchoolyear(Period $period, $categoryId, $locked = null)
    {
        if(is_null($locked)) {
            return $this->stages->filter(function($stage) use (&$categoryId, &$period) {
                return $stage->getProposal()->getCategory()->getCategories()->exists(function($key, $category) use (&$categoryId) {
                    return $category->getId() === (int)$categoryId;
                }) && $period->sameSchoolyear($stage->getProposal()->getPeriod());
            })->count();
        }
        else {
            return $this->stages->filter(function($stage) use (&$categoryId, &$locked, &$period) {
                return $stage->getLocked() === $locked && $stage->getProposal()->getCategory()->getCategories()->exists(function($key, $category) use (&$categoryId) {
                    return $category->getId() === (int)$categoryId;
                }) && $period->sameSchoolyear($stage->getProposal()->getPeriod());
            })->count();
        }        
    }

    public function countStagesInPeriod(Period $period, $locked = null)
    {
        if(is_null($locked)) {
            return $this->stages->filter(function($stage) use (&$period) {                
                return $stage->getProposal()->getPeriod()->getId() === $period->getId();
            })->count();

src/Lulhum/UserBundle/Resources/views/Admin/confirm.html.twig
{# src/Lulhum/UserBundle/Resources/views/Admin/confirm.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
  Confirmation - {{ parent() }}
{% endblock %}

{% block main %}
	<div class="panel panel-danger" >
		<div class="panel-heading" >
			{{ message }}
		</div>
		<div class="panel-body" >
			{{ user.fullname }}
		</div>
		<div class="panel-footer" >
			{{ form_start(form) }}
			{{ form_widget(form.Confirmer) }}
			<a href="{{ path('lulhum_user_admin_userlist') }}" class="btn btn-primary" >Annuler</a>
			{{ form_rest(form) }}
			{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

src/Lulhum/UserBundle/Resources/views/Admin/groupactionchangepromotion.html.twig
{# src/Lulhum/UserBundle/Resources/views/Admin/groupactionchangepromotion.html.twig #}

{% extends "LulhumRepartitionMedecineBundle:Admin:groupaction.html.twig" %}

{% block groupactionbodytitle %}Utilisateurs - {{ parent() }}{% endblock %}

{% block groupactionaffectedentities %}Utilisateurs affectés{% endblock %}

{% block bodyfooter %}
	<div class="panel-footer" >
		{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
		<div class="form-group" >
			{{ form_label(form.promotion, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
			{{ form_errors(form.promotion) }}
			<div class="col-md-10" >
				{{ form_widget(form.promotion, {'attr': {'class': 'form-control', 'size': '2'}}) }}
			</div>
		</div>
		<button type="submit" class="btn btn-primary" >Modifier</button>
		{{ form_rest(form) }}
		{{ form_end(form) }}
	</div>
{% endblock %}

src/Lulhum/UserBundle/Resources/views/Admin/groupmail.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/mail.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
Mails groupés - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3>Envoi de mails groupés</h3>
{% endblock %}

{% block body %}
	{% for key, messages in app.session.flashbag.all() %}
		{% for message in messages %}
			<div class="alert alert-{{ key }} alert-dismissible">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
		{% endfor %}
	{% endfor %}
	{{ form_start(form) }}
	<div class="form-group" >
		{{ form_label(form.promotions) }}
		{{ form_errors(form.promotions) }}
		{{ form_widget(form.promotions, {'attr': {'class': 'form-control', 'size': '2'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(form.group) }}
		{{ form_errors(form.group) }}
		{{ form_widget(form.group, {'attr': {'class': 'form-control'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(form.title) }}
		{{ form_errors(form.title) }}
		{{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
	</div>
	{% include "LulhumCMSBundle:Admin:wisihtml_toolbar.html.twig" %}
	<div class="form-group" >
		{{ form_label(form.content) }}
		{{ form_errors(form.content) }}
		{{ form_widget(form.content, {'attr': {'placeholder': 'Votre texte ici...', 'class': 'form-control vresize', 'style': 'height:260px'}}) }}
	</div>
	<button type="submit" class="btn btn-primary" >Envoyer</button>
	{{ form_rest(form) }}
	{{ form_end(form) }}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{% javascripts '@wysihtml' %}
	<script type="text/javascript" src="{{ asset_url }}"></script>
	{% endjavascripts %}
	<script type="text/javascript" >
	$(document).ready(function() {	
		var editor = new wysihtml5.Editor('lulhum_user_groupmail_content', {
			toolbar: 'toolbar',
			parserRules:  wysihtml5ParserRules
		});
	});
	</script>
{% endblock %}

src/Lulhum/UserBundle/Resources/views/Admin/listusers.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/listusers.html.twig #}

{% extends "LulhumRepartitionMedecineBundle:Admin:groupactionlist.html.twig" %}

{% block title %}
  Utilisateurs - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3>Liste des utilisateurs</h3>
	<hr/>
	{{ form_start(filterForm, {'attr': {'class': 'form-inline'}}) }}
	{{ form_errors(filterForm) }}
	<div class="form-group" >
		{{ form_label(filterForm.promotions, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.promotions) }}
		{{ form_widget(filterForm.promotions, {'attr': {'class': 'form-control', 'multiple': 'true', 'size': '2'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(filterForm.group, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.group) }}
		{{ form_widget(filterForm.group, {'attr': {'class': 'form-control', 'size': '2'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(filterForm.periods, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.periods) }}
		{{ form_widget(filterForm.periods, {'attr': {'class': 'form-control', 'multiple': 'true', 'size': '2'}}) }}
	</div>
	<div class="form-group" >
		{{ form_label(filterForm.categories, null, {'label_attr': {'class': 'control-label'}}) }}
		<br/>
		{{ form_errors(filterForm.categories) }}
		{{ form_widget(filterForm.categories, {'attr': {'class': 'form-control', 'multiple': 'true', 'size': '2'}}) }}
	</div>
	<br/>
	<div style="margin-top:10px" >
		<div class="form-group" >
			{{ form_widget(filterForm.filtrer, {'attr': {'class': 'btn btn-primary' }}) }}
		</div>
		<div class="form-group" >
			<a class="btn btn-primary" href="{{ path('lulhum_user_admin_userlist_resetfilter') }}" >Filtre par défaut</a>
		</div>
		<div class="form-group" >
			<a class="btn btn-success" href="{{ path('lulhum_user_admin_user_add') }}" >Nouvel Utilisateur</a>
		</div>
		<div class="btn-group">
			<a class="btn btn-default" href="{{ path('lulhum_user_admin_export', {'ext': 'xlsx'}) }}" data-export="table" >
				<span class="glyphicon glyphicon-export" ></span>
			</a>
			<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-export="toggle" aria-haspopup="true" aria-expanded="false">
				<span class="caret"></span>
				<span class="sr-only">Toggle Dropdown</span>
			</button>
			<ul class="dropdown-menu">
				<li class="active" >
					<a data-export="format" data-format="xlsx">
						xlsx
					</a>
				</li>
				<li>
					<a data-export="format" data-format="xls">
						xls
					</a>
				</li>
				<li>
					<a data-export="format" data-format="csv">
						csv
					</a>
				</li>
				<li>
					<a data-export="format" data-format="html">
						html
					</a>
				</li>
			</ul>
		</div>
	</div>	
	{{ form_rest(filterForm) }}
	{{ form_end(filterForm) }}
{% endblock %}

{% block groupactionlisthead %}
	<th>Nom</th>
	<th>Prénom</th>
	<th>Promotion</th>
	<th>Groupe</th>
	{% for period in filter.periods %}
		<th>{{ period }}</th>
	{% endfor %}
	{% for category in filter.categories %}
		<th>{{ category }}</th>
	{% endfor %}
	<th>Actions</th>
{% endblock %}

{% block groupactionlistbody %}
	{% set u = userList[loop.index0] %}
	<td><a href="{{ path('lulhum_user_admin_user', {'id': u.id}) }}">{{ u.lastname }}</a></td>
	<td>{{ u.firstname }}</td>
	<td>{{ u.textPromotion }}</td>
	<td>{{ u.repartitionGroup }}</td>

	{% for period in filter.periods %}
		<td>
			{% if u.hasStageInPeriod(period) and u.getStageInPeriod(period).locked %}
				<span class="label label-success" >Oui</span>
			{% else %}
				<span class="label label-danger" >Non</span>
			{% endif %}
		</td>
	{% endfor %}
	{% for category in filter.categories %}
		<td>
			{% if u.countStagesInCategory(category.id, true) %}
				<span class="label label-success" >Oui</span>
			{% else %}
				<span class="label label-danger" >Non</span>
			{% endif %}
		</td>
	{% endfor %}

	<td>					
		<a href="{{ path('lulhum_user_admin_user_edit', {'id': u.id}) }}" >
			<span class="glyphicon glyphicon-edit" ></span>
		</a>
		{% if u.hasRole('ROLE_ADMIN') %}
			<a href="{{ path('lulhum_user_admin_user_switchadmin', {'id': u.id}) }}" class="text-success" >
				<span class="glyphicon glyphicon-eye-open" ></span>
			</a>
		{% else %}
			<a href="{{ path('lulhum_user_admin_user_switchadmin', {'id': u.id}) }}" class="text-danger" >
				<span class="glyphicon glyphicon-eye-close" ></span>
			</a>
		{% endif %}
		<a href="{{ path('lulhum_user_admin_user_delete', {'id': u.id}) }}" class="text-danger" >
			<span class="glyphicon glyphicon-remove" ></span>
		</a>
	</td>
{% endblock %}

{% block bodyunder %}
	<div>
		<span class="text-success" >
			<span class="glyphicon glyphicon-eye-open" ></span>
		</span>
		Administrateur -
		<span class="text-primary" >
			<span class="glyphicon glyphicon-edit" ></span>
		</span>
		Éditer l'utilisateur -
		<span class="text-danger" >
			<span class="glyphicon glyphicon-remove" ></span>
		</span>
		Supprimer l'utilisateur
	</div>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script type="text/javascript" >
	$(document).ready(function() {
		$('[data-export="format"]').click(function(e) {
			var ext = $(this).attr('data-format');
			$('[data-export="format"]').each(function() {
				$(this).parent().attr('class', '');
			});
			$(this).parent().attr('class', 'active');
			$('[data-export="table"]').each(function() {
				$(this).attr('href', $(this).attr('href').replace(/\.[a-z]+$/, '.'+ext));
			});
			$(this).parents('div.btn-group').children('[data-export="toggle"').dropdown('toggle');
			e.preventDefault();
			return false;			
		});
	});
	</script>
{% endblock %}

src/Lulhum/UserBundle/Resources/views/Admin/user.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/listusers.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
  {{ user.fullname }} - {{ parent() }}
{% endblock %}

{% block body %}
	
	{% include "FOSUserBundle:Profile:show_content.html.twig" %}
	
	<div class="row top-buffer" >
		<div class="col-md-12" >
			<p><a href="{{ path('lulhum_user_admin_user_edit', {'id': user.id}) }}">Modifier le profil</a></p>
			<p><a href="{{ path('lulhum_user_admin_userlist') }}">Retour à la liste</a></p>
		</div>
	</div>
	
{% endblock %}

src/Lulhum/UserBundle/Resources/views/Admin/user_type.html.twig
<div class="form-group" >
	{{ form_label(form.lastname, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.lastname) }}
	<div class="col-md-10" >
		{{ form_widget(form.lastname, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
<div class="form-group" >
	{{ form_label(form.firstname, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.firstname) }}
	<div class="col-md-10" >
		{{ form_widget(form.firstname, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
<div class="form-group" >
	{{ form_label(form.email, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.email) }}
	<div class="col-md-10" >
		{{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
<div class="form-group" >
	{{ form_label(form.studentId, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.studentId) }}
	<div class="col-md-10" >
		{{ form_widget(form.studentId, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
<div class="form-group" >
	{{ form_label(form.phone, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.phone) }}
	<div class="col-md-10" >
		{{ form_widget(form.phone, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
{% if form.promotion is defined %}
	<div class="form-group" >
		{{ form_label(form.promotion, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
		{{ form_errors(form.promotion) }}
		<div class="col-md-10" >
			{{ form_widget(form.promotion, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
{% endif %}
{% if form.repartitionGroup is defined %}
	<div class="form-group" >
		{{ form_label(form.repartitionGroup, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
		{{ form_errors(form.repartitionGroup) }}
		<div class="col-md-10" >
			{{ form_widget(form.repartitionGroup, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
{% endif %}
{% if form.repartitionGroupForce is defined %}
	<div class="form-group" >
		{{ form_label(form.repartitionGroupForce, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
		{{ form_errors(form.repartitionGroupForce) }}
		<div class="col-md-10" >
			<div class="checkbox" >
				<label>
					{{ form_widget(form.repartitionGroupForce) }}
				</label>
			</div>
		</div>
	</div>
{% endif %}
<div class="form-group" >
	{{ form_label(form.present, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.present) }}
	<div class="col-md-10" >
		{{ form_widget(form.present, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
<div class="form-group" >
	{{ form_label(form.internetAccess, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.internetAccess) }}
	<div class="col-md-10" >
		{{ form_widget(form.internetAccess, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>
<div class="form-group" >
	{{ form_label(form.proxy, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
	{{ form_errors(form.proxy) }}
	<div class="col-md-10" >
		<div class="input-group" >
			{{ form_widget(form.proxy, {'attr': {'class': 'form-control'}}) }}
			<span class="input-group-btn" >
				<button class="btn btn-default"
					type="button"
					id="lulhum-user-search" 
					data-container="body"
					data-toggle="popover"
					data-placement="left"
					data-title="Rechercher un utilisateur"
					data-html="true" >
					<span class="glyphicon glyphicon-search" ></span>
				</button>
			</span>
		</div>
	</div>
</div>
{% if form.plainPassword is defined %}
	{% for passwordField in form.plainPassword %}
		<div class="form-group" >
			{{ form_label(passwordField, null, {'label_attr': {'class': 'control-label col-md-2'}}) }}
			{{ form_errors(passwordField) }}
			<div class="col-md-10" >
				{{ form_widget(passwordField, {'attr': {'class': 'form-control'}}) }}
			</div>
		</div>
	{% endfor %}
{% endif %}

src/Lulhum/UserBundle/Resources/views/Admin/useradd.html.twig
{# src/Lulhum/UserBundle/Resources/views/Admin/useradd.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
	Nouvel utilisateur - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<h3 class="panel-title">Ajouter un nouvel utilisateur</h3>
{% endblock %}

{% block body %}
	{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
	{{ include('LulhumUserBundle:Admin:user_type.html.twig') }}
	<button class="btn btn-success" type="submit" >Ajouter</button>
	{{ form_rest(form) }}
	{{ form_end(form) }}	
{% endblock %}

src/Lulhum/UserBundle/Resources/views/Admin/useredit.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/useredit.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::adminlayout.html.twig" %}

{% block title %}
  {{ user.fullname }} - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	<div class="panel-title" >Modifier</div>
{% endblock %}

{% block body %}
	{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
	{{ include('LulhumUserBundle:Admin:user_type.html.twig') }}
	<button class="btn btn-success" type="submit" >Modifier</button>
	{{ form_rest(form) }}
	{{ form_end(form) }}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{% javascripts '@LulhumRepartitionMedecineBundle/Resources/public/js/search-select-popover.js' %}
	<script type="text/javascript" src="{{ asset_url }}"></script>
	{% endjavascripts %}
	<script type="text/javascript">
	$(document).ready(function() {
		activateSearchSelectPopover();
	});
	</script>
{% endblock %}

src/Lulhum/UserBundle/Resources/views/Admin/usermenupromotion.html.twig
{# src/Lulhum/RepartitionMedecineBundle/Resources/views/Admin/usermenupromotion.html.twig #}

{% for key, promotion in promotions %}
	<li>
		<a href="{{ path('lulhum_user_admin_userlist_promotion', {'promotion': key}) }}">
			{{ promotion }}
		</a>
	</li>
{% endfor %}