src/Lulhum/CMSBundle/Entity/Page.php
<?php

namespace Lulhum\CMSBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\SecurityContext;

/**
 * Page
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Lulhum\CMSBundle\Repository\PageRepository")
 */
class Page
{
    const VISIBILITIES = array(
        'ROLE_USER' => 'Utilisateur connecté',
        'ROLE_ADMIN' => 'Administrateur',
    );

    const SPECIAL_BLOCKS = array(
        'facebook' => array(
            'description' => 'Intégration du plugin Facebook',
            'markup' => '[[fb:facebook]]',
            'pattern' => '/\[\[fb:([[:graph:]]*)\]\]/',
            'html' =>'<div class="fb-root" >$1</div>',
        ),
        'youtube' => array(
            'description' => 'Intégration de vidéos Youtube',
            'markup' => '[[yt:youtubeid]]',
            'pattern' => '/\[\[yt:([[:alnum:]]*)\]\]/',
            'html' => '<div class="youtube-embed">$1</div>',
        ),
    );
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var string
     *
     * @ORM\Column(name="visibility", type="string", length=255, nullable=true)
     */
    private $visibility;

    /**
     * @var string
     *
     * @ORM\Column(name="menu", type="string", length=255, nullable=true)
     */
    private $menu;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Page
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Page
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }

    public function getContentSpecialBlocks()
    {
        $result = $this->content;
        foreach(self::SPECIAL_BLOCKS as $block) {
            $result = preg_replace($block['pattern'], $block['html'], $result);
        }

        return $result;
    }

    /**
     * Set visibility
     *
     * @param array $visibility
     * @return Page
     */
    public function setVisibility($visibility)
    {
        $this->visibility = $visibility;

        return $this;
    }

    /**
     * Get visibility
     *
     * @return array 
     */
    public function getVisibility()
    {
        return $this->visibility;
    }

    /**
     * Set menu
     *
     * @param string $menu
     * @return Page
     */
    public function setMenu($menu)
    {
        $this->menu = $menu;

        return $this;
    }

    /**
     * Get menu
     *
     * @return string 
     */
    public function getMenu()
    {
        return $this->menu;
    }

    public function __toString()
    {
        return $this->title;
    }

    public function isVisible(SecurityContext $context)
    {
        return is_null($this->visibility) || $context->isGranted($this->visibility);
    }

    public function textVisibility()
    {
        return is_null($this->visibility) ? 'Publique' : self::VISIBILITIES[$this->visibility];
    }

    public function getSpecialBlocks()
    {
        return self::SPECIAL_BLOCKS;
    }

}

src/Lulhum/CMSBundle/Resources/views/Page/menu.html.twig
{# src/Lulhum/CMSBundle/Resources/views/Page/menu.html.twig #}

{% for key, item in menu %}
	{% if item|length > 1 %}
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				{{ key }}
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
				{% for entry in item %}
					<li>
						<a href="{{ path('lulhum_cms_page', {'id': entry.id}) }}" >
							{{ entry.title }}
						</a>
					</li>
				{% endfor %}
			</ul>
		</li>
	{% else %}
		<li>
			<a href="{{ path('lulhum_cms_page', {'id': item[0].id}) }}">
				{{ item[0].menu }}
			</a>
		</li>
	{% endif %}
{% endfor %}

src/Lulhum/CMSBundle/Resources/views/Page/page.html.twig
{# src/Lulhum/CMSBundle/Resources/views/page.html.twig #}

{% extends "LulhumRepartitionMedecineBundle::layout.html.twig" %}

{% block title %}
	{{ page.title }} - {{ parent() }}
{% endblock %}

{% block bodytitle %}
	{{ page.title }}
{% endblock %}

{% block body %}
	{% for key, messages in app.session.flashbag.all() %}
		{% for message in messages %}
			<div class="alert alert-{{ key }} alert-dismissible">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
		{% endfor %}
	{% endfor %}
	{{ page.contentSpecialBlocks|purify }}	
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script type="text/javascript" >
	$(document).ready(function() {
		var $fbPlugins = $('div.fb-root');
		if($fbPlugins.length != 0) {
			var prototype = '<div class="fb-page" data-href="https://www.facebook.com/__fblink__" data-tabs="timeline" data-width="500px" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/__fblink__"><a href="https://www.facebook.com/__fblink__">Facebook</a></blockquote></div></div>';
			$fbPlugins.first().attr('id', 'fb-root');
			$fbPlugins.each(function () {
				var $pluginAnchor = $(this);
				var link = $pluginAnchor.html();
				$pluginAnchor.html('');
				var $plugin = $(prototype.replace(/__fblink__/g, link));
				$pluginAnchor.after($plugin);
			});		
			
			(function(d, s, id) {
				var js, fjs = d.getElementsByTagName(s)[0];
				if (d.getElementById(id)) return;
				js = d.createElement(s);
				js.id = id;
				js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
				fjs.parentNode.insertBefore(js, fjs);
			} (document, 'script', 'facebook-jssdk'));
		}

		var $ytPlugins = $('div.youtube-embed');
		if($ytPlugins.length != 0) {
			var prototype = '<iframe width="560" height="315" src="https://www.youtube.com/embed/__youtubeid__?rel=0" frameborder="0" allowfullscreen></iframe>';
			$ytPlugins.each(function () {
				var $pluginAnchor = $(this);
				var link = $pluginAnchor.html();
				$pluginAnchor.html('');
				var $plugin = $(prototype.replace(/__youtubeid__/g, link));
				$pluginAnchor.append($plugin);
			});
		}
	});	
	</script>
{% endblock %}